// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.12.4
// source: proto/todo.proto

/* eslint-disable */

export const protobufPackage = 'todoproto';

export interface getTodosRequest {}

export interface deleteSuccessMessage {
  message: string;
}

export interface getTodoByIdRequest {
  uuid: string;
}

export interface deleteTodoByIdRequest {
  uuid: string;
}

export interface getTodosResponse {
  todos: Todo[];
}

export interface Todo {
  uuid: string;
  name: string;
  description: string;
}

export interface CreateTodoDto {
  name: string;
  description: string;
}

export interface TodoService {
  getTodos(request: getTodosRequest): getTodosResponse;
  getTodoById(request: getTodoByIdRequest): Todo;
  createTodo(request: CreateTodoDto): Todo;
  updateTodo(request: Todo): Todo;
  deleteTodo(request: deleteTodoByIdRequest): deleteSuccessMessage;
}
